template: 0
split: realtoxicityprompts.toxic
data_file: ./data/toxicity/user_prompts/toxic.jsonl
out_file: ./results/toxicity/user_prompts/generations/${model_config.model}/toxic-template-${.template}-generations.jsonl
max_tokens: 150
n: 25
t: 1
api: null
