template: 1
split: toxic.gpt4
data_file: ./data/toxicity/user_prompts/toxic.jsonl.gpt4.n=25.out1.split.annotated.jsonl.filtered.jsonl
out_file: ./results/toxicity/user_prompts/generations/${model_config.model}/toxic-gpt4-template-${.template}-generations.jsonl
max_tokens: 150
n: 25
t: 1
save_interval: 100
api: null