data_dir: ./data/fairness/fairness_data/
prompt_file: adult_32_200_train_base_rate_1.0.jsonl
gt_file: gt_labels_adult_32_200_train_base_rate_1.0.npy
sensitive_attr_file: sensitive_attr_adult_32_200_train_base_rate_1.0.npy
dataset: adult
out_file: ./results/fairness/results/${model_config.model}/few_shot_tr_br_1.0.json