data_dir: ./data/fairness/fairness_data/
prompt_file: adult_16_200_train_br_0.0_test_br_0.5.jsonl
gt_file: gt_labels_adult_16_200_train_br_0.0_test_br_0.5.npy
sensitive_attr_file: sensitive_attr_adult_16_200_train_br_0.0_test_br_0.5.npy
dataset: adult
out_file: ./results/fairness/results/${model_config.model}/few_shot_16_fair_demon.json